### ISSUE TITLE
expose directory asterisk modules

### ISSUE THREAD

**Issue by pnhat997** [ugoviti/izpbx#54]
expose directory /usr/lib64/asterisk/modules

**Comment by ugoviti** [comment]
Hi, what do you mean?

you want just mount some files into /usr/lib64/asterisk/modules?

if so, you can create docker-compose.override.conf and add for example:

```
version: '3'

services:
  izpbx:
    volumes:
    - ./data/asterisk/modules/yourfile.so:/usr/lib64/asterisk/modules/yourfile.so:ro
```

Do you need this?

Kind Regards
